language: python
python:
  - 2.7
services:
  - mysql
before_install:
  - mv sophon/config_default.py sophon/config.py
before_script:
  - mysql -e 'create database sophon;'
install:
  - python setup.py install
  - pip install coveralls
  - pip install pytest-cov
script:
  - pylint --rcfile=.pylintrc sophon --ignore=config.py
  - pylint --rcfile=.pylintrc tests
  - py.test --cov=sophon tests/
after_success:
  - coveralls
